### PR TITLE
Prevent some global arrays when distributing

### PR DESCRIPTION
**Pull request by blattms**
These will be some drive by shootings while working on just having the whole grid on one process.
Basically I am using jenkins to test my code.

### CODE REVIEW

**Comment by blattms** [comment]
jenkins build this please

**Comment by blattms** [comment]
jenkins build this please

**Comment by blattms** [comment]
jenkins build this please

**Comment by blattms** [comment]
jenkins build this please

**Comment by blattms** [comment]
jenkins run norne spe please

**Comment by blattms** [comment]
Mmh. The last test failed with
```
~/post-builder/workspace/opm-grid-PR-builder ~/post-builder/workspace/opm-grid-PR-builder
/var/lib/jenkins/post-builder/workspace/opm-grid-PR-builder/deps/opm-simulators/jenkins/run-spe.sh: line 19: /var/lib/jenkins/post-builder/workspace/opm-grid-PR-builder/mpi/build-opm-simulators/bin/flow_legacy: No such file or directory
Build step 'Execute shell' marked build as failure
Archiving artifacts
Recording test results
[GNU C Compiler (gcc)] Skipping execution of recorder since overall result is 'FAILURE'
Setting status of 2366f16b49a29d41fe995a2035966d553f5fc839 to FAILURE with url https://ci.opm-project.org/job/opm-grid-PR-builder/11/ and message: 'Build finished. '
Finished: FAILURE
```
Why would it expect `flow_legacy`?

**Comment by atgeirr** [comment]
> Why would it expect `flow_legacy`?

Because it has not been updated. Fix in https://github.com/OPM/opm-simulators/pull/1946

**Comment by blattms** [comment]
Well, if it is just spe then let us run norne.

**Comment by blattms** [comment]
jenkins run norne please

**Comment by blattms** [comment]
Norne run through. Any comments?
Otherwise I will join the happy self-merge-community. speak_no_evil

**Comment by blattms** [comment]
A rebase was needed.

**Comment by blattms** [comment]
jenkins run norne please

**Comment by blattms** [comment]
Well, these seemingly simply nitpicks. Here a blank there a blank and then other PRs have to be rebased again and agian.
Here we go again. Rebased. At least the conflicts were simple to resolve.

**Comment by blattms** [comment]
jenkins run norne please

**Comment by atgeirr** [comment]
This dropped off my radar for a while, but I assume it is still wanted @blattms?

**Comment by blattms** [comment]
I guess it is too late to merge this now and I assume that all the changes are also included in PR #389 (or not needed once that is merged). Therefore I am closing this.

**Pull request closed without merging**
