### PR TITLE
[bugfix] make tests compile for PolyhedralGrid with DUNE 2.5

### PR DESCRIPTION
**Pull request by dr-robertk**
This PR fixes an issue raised by blattms. 

@blattms: Please check.

### CODE REVIEW

**Comment by blattms** [comment]
Unfortunately, I still have issues:
```
In file included from /home/mblatt/DUNE-2.5/opm-grid/dune/grid/polyhedralgrid/gridview.hh:14:0,
                 from /home/mblatt/DUNE-2.5/opm-grid/dune/grid/polyhedralgrid/grid.hh:30,
                 from /home/mblatt/DUNE-2.5/opm-grid/dune/grid/polyhedralgrid.hh:1,
                 from /home/mblatt/DUNE-2.5/opm-grid/tests/grid_test.cc:8:
/home/mblatt/DUNE-2.5/opm-grid/dune/grid/polyhedralgrid/indexset.hh: In instantiation of ‘Dune::PolyhedralGridIndexSet<dim, dimworld>::IndexType Dune::PolyhedralGridIndexSet<dim, dimworld>::subIndex(const Entity&, int, unsigned int) const [with Entity = Dune::Entity<1, 3, const Dune::PolyhedralGrid<3, 3>, Dune::PolyhedralGridEntity>; int dim = 3; int dimworld = 3; Dune::PolyhedralGridIndexSet<dim, dimworld>::IndexType = int]’:
/home/mblatt/DUNE-2.5/dune-grid/dune/grid/test/staticcheck.hh:434:9:   required from ‘GridViewInterface<GridView>::check(const GridView&)::<lambda(auto:9)> [with auto:9 = std::integral_constant<int, 1>; GridView = Dune::GridView<Dune::PolyhedralGridViewTraits<3, 3, (Dune::PartitionIteratorType)4u> >]’
/home/mblatt/DUNE-2.5/dune-common/dune/common/hybridutilities.hh:262:96:   required from ‘constexpr void Dune::Hybrid::Impl::forEachIndex(Range&&, F&&, std::integer_sequence<Index, i ...>) [with Range = std::integer_sequence<int, 0, 1, 2, 3>; F = GridViewInterface<GridView>::check(const GridView&) [with GridView = Dune::GridView<Dune::PolyhedralGridViewTraits<3, 3, (Dune::PartitionIteratorType)4u> >]::<lambda(auto:9)>; Index = long unsigned int; Index ...i = {0ul, 1ul, 2ul, 3ul}]’
/home/mblatt/DUNE-2.5/dune-common/dune/common/hybridutilities.hh:271:73:   required from ‘constexpr void Dune::Hybrid::Impl::forEach(Range&&, F&&, Dune::PriorityTag<1ul>) [with Range = std::integer_sequence<int, 0, 1, 2, 3>; F = GridViewInterface<GridView>::check(const GridView&) [with GridView = Dune::GridView<Dune::PolyhedralGridViewTraits<3, 3, (Dune::PartitionIteratorType)4u> >]::<lambda(auto:9)>; typename std::enable_if<Dune::IsIntegralConstant<decltype (Dune::Hybrid::size(declval<Range>()))>::value, int>::type <anonymous> = 0]’
/home/mblatt/DUNE-2.5/dune-common/dune/common/hybridutilities.hh:309:82:   required from ‘constexpr void Dune::Hybrid::forEach(Range&&, F&&) [with Range = std::integer_sequence<int, 0, 1, 2, 3>; F = GridViewInterface<GridView>::check(const GridView&) [with GridView = Dune::GridView<Dune::PolyhedralGridViewTraits<3, 3, (Dune::PartitionIteratorType)4u> >]::<lambda(auto:9)>]’
/home/mblatt/DUNE-2.5/dune-grid/dune/grid/test/staticcheck.hh:444:6:   required from ‘static void GridViewInterface<GridView>::check(const GridView&) [with GridView = Dune::GridView<Dune::PolyhedralGridViewTraits<3, 3, (Dune::PartitionIteratorType)4u> >]’
/home/mblatt/DUNE-2.5/dune-grid/dune/grid/test/staticcheck.hh:468:35:   required from ‘GridViewInterface<GridView>::GridViewInterface() [with GridView = Dune::GridView<Dune::PolyhedralGridViewTraits<3, 3, (Dune::PartitionIteratorType)4u> >]’
/home/mblatt/DUNE-2.5/dune-grid/dune/grid/test/staticcheck.hh:523:5:   required from ‘static void GridInterface<Grid>::check(const Grid&) [with Grid = Dune::PolyhedralGrid<3, 3>]’
/home/mblatt/DUNE-2.5/dune-grid/dune/grid/test/staticcheck.hh:577:7:   required from ‘GridInterface<Grid>::GridInterface() [with Grid = Dune::PolyhedralGrid<3, 3>]’
/home/mblatt/DUNE-2.5/dune-grid/dune/grid/test/gridcheck.hh:886:3:   required from ‘void gridcheck(Grid&) [with Grid = Dune::PolyhedralGrid<3, 3>]’
/home/mblatt/DUNE-2.5/opm-grid/tests/grid_test.cc:111:23:   required from ‘void testGrid(Grid&, const string&) [with Grid = Dune::PolyhedralGrid<3, 3>; std::string = std::basic_string<char>]’
/home/mblatt/DUNE-2.5/opm-grid/tests/grid_test.cc:165:40:   required from here
/home/mblatt/DUNE-2.5/opm-grid/dune/grid/polyhedralgrid/indexset.hh:69:92: error: ‘const class Dune::PolyhedralGridEntity<1, 3, const Dune::PolyhedralGrid<3, 3> >’ has no member named ‘subEntity’
         return index( grid().getRealImplementation( entity ).template subEntity< 1 > ( i ) );
                                                                                            ^
/home/mblatt/DUNE-2.5/opm-grid/dune/grid/polyhedralgrid/indexset.hh:71:100: error: ‘const class Dune::PolyhedralGridEntity<1, 3, const Dune::PolyhedralGrid<3, 3> >’ has no member named ‘subEntity’
         return index( grid().getRealImplementation( entity ).template subEntity< dimension > ( i ) );
```

**Comment by dr-robertk** [comment]
@blattms: Now it should compile.

**Comment by blattms** [comment]
great thanks!
I forgot to push f027378 to my branch/PR. Would you mind cherry-picking? Then your PR includes everything needed.

**Comment by dr-robertk** [comment]
I pulled your PR and rebased. You can just include my patch into your PR.

**Comment by dr-robertk** [comment]
@blattms: I lost overview which one of the PRs is the actual one that should be merged?

**Comment by blattms** [comment]
This one as it includes my changes and has yours in it.

Closes #249

**Comment by dr-robertk** [comment]
Is is ok to merge then?

**Comment by atgeirr** [comment]
> Is is ok to merge then?

As long as it does not cause problem with older Dune versions, I'm fine with it (I assume that has been checked?)

**Comment by dr-robertk** [comment]
I can check with 2.4 and 2.5 but I recommend to drop support for 2.3 at this point.

**Comment by atgeirr** [comment]
> I recommend to drop support for 2.3 at this point.

I can agree with the recommendation in general, but should not drop it without discussion (and did we not have this discussion recently? I cannot remember what the consensus was).

Other than that: will merging this PR drop 2.3 support?

**Comment by blattms** [comment]
I do not think so, but I can recheck with 2.3. Or I guess that Travis
does this automatically, does it not?

**Comment by blattms** [comment]
Travis says:
```
Version 2.3.1 of dune-common from /home/travis/build/OPM/dune-common/dune.module
```
So yes, everything that works with travis is checked against DUNE 2.3.

**Comment by andlaus** [comment]
> I can agree with the recommendation in general, but should not drop it without discussion (and did we not have this discussion recently? I cannot remember what the consensus was).

I'm all for dropping support for Dune 2.3. If I remember correctly, the reason to keep it was that this is the Dune version shipped with Ubuntu 14.04 LTS. (maybe we should leave 14.04 behind as well?)

**Comment by atgeirr** [comment]
First things first: since Travis is happy with this PR, it does not break 2.3 and can be merged.

Second: while Travis, one of our main platforms (Ubuntu 14.04) and potentially others like Statoil are on 2.3 we'll have to support it. When 16.04 can be made our primary Ubuntu version (how is that Eigen situation anyway) *and* Travis etc. are off 2.3, we can raise the minimum supported version. Looking forward to it, but all these small pieces must be in place. (With apologies if I forgot something important.)

**Comment by dr-robertk** [comment]
Thanks. Maybe that the point where we DUNE version is raised we might want to jump to 2.5.

**Comment by andlaus** [comment]
I know that at the moment there are still a few good reasons for keeping 2.3 support. on the other hand, it significantly increases the area of attack relevant for testing.

> (how is that Eigen situation anyway)

if you don't install the "libeigen3-dev" package, everything is fine except for a few warnings within the cloned-by-the-buildsystem copy of Eigen...

**Comment by atgeirr** [comment]
Merging this causes a test failure (assert() triggered) in debug mode (so it was not caught by automatic testing):

```
atgeirr@galadriel:~/opm-build-debug/opm-grid-build$ bin/grid_test 
Assertion failed: (codim >= EntitySeedArg::dimension), function subEntitySeed, file /Users/atgeirr/opm-build-debug/opm-grid/dune/grid/polyhedralgrid/grid.hh, line 916.
```

It seems to me perhaps this assert is wrong, and should instead be:
```
      assert( codim >= EntitySeedArg::codimension );
```
@dr-robertk can you verify and fix this?

**Comment by pgdr** [comment]
Confirmed:

```
grid_test: /var/jenkins/workspace/opm-grid-install-RH6/dune/grid/polyhedralgrid/grid.hh:916:
typename Dune::PolyhedralGrid<dim, dimworld>::Codim<codim>::EntitySeed
Dune::PolyhedralGrid<dim, dimworld>::subEntitySeed(const EntitySeedArg&, int) const [with int codim = 1;
EntitySeedArg = Dune::PolyhedralGridEntitySeed<0, const Dune::PolyhedralGrid<3, 3> >;
int dim = 3;
int dimworld = 3;
typename Dune::PolyhedralGrid<dim, dimworld>::Codim<codim>::EntitySeed = Dune::PolyhedralGridEntitySeed<1, const Dune::PolyhedralGrid<3, 3> >]:
Assertion `codim >= EntitySeedArg::dimension' failed.
```

**Pull request merged**
