### PR TITLE
Add nnc connections old boost fix periodic

### PR DESCRIPTION
**Pull request by akva2**
Continuing this PR series.. (#355, #356).

This takes care of the test failures in opm-upscaling.

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this ewoms=466 please

**Comment by akva2** [comment]
jenkins build this ewoms=466 please

**Comment by akva2** [comment]
jenkins build this ewoms=466 opm-simulators=1728 update_data please

**Comment by akva2** [comment]
jenkins build this ewoms=466 opm-simulators=1728 opm-tests=93 please

**Comment by akva2** [comment]
@blattms i've been tasked with landing this as @atgeirr is on sick leave. what is the status of your review? are you (reasonably) happy or are there more things that needs addressing?

**Comment by blattms** [comment]
Looks like everything important was addressed.

**Comment by alfbr** [comment]
I just wanted a quick check on performance, as the accidental trigging indicated we may have a regression. Unfortunately, this is our first test of the system for multi-PR set-up, so a bit of trial and error. Will attempt a new one here.

**Comment by alfbr** [comment]
benchmark ewoms=466

**Comment by bska** [comment]
> jenkins build this [...] update_data please

We will probably have to re-update the reference solutions to account for PR OPM/opm-common#548 (and its associate PR OPM/opm-tests#94) being merged in the interim.

**Comment by ytelses** [comment]
Benchmark result overview: 




| Test    | Configuration                              | Relative |
| ------- | ------------------------------------------ | -------- |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 1 | 1.053    |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 8 | 1.007    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1 | 1.002    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8 | 1.326    |
* Speed-up = Total time master / Total time pull request. Above 1.0 is an improvement. *



View result details @ https://www.ytelses.com/opm/?page=result&id=224

**Comment by akva2** [comment]
jenkins build this ewoms=466 opm-simulators=1728 update_data please

**Comment by akva2** [comment]
jenkins build this ewoms=466 opm-simulators=1728 opm-tests=93 please

**Comment by akva2** [comment]
any objections to hitting the buttons?

**Comment by alfbr** [comment]
Unfortunately, multi-PR benching does not work yet, but do not let that stop it. No objections from me.

**Comment by akva2** [comment]
both the tester and the guy who reviewed the code has signed off, i'll consider it enough.

**Pull request merged**
