### PR TITLE
fixed: quell unused variable warning without MPI

### PR DESCRIPTION
**Pull request by akva2**
just some janitoring..

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this serial please

**Review by blattms — APPROVED** [review]
Apart from initialization `procs` is not used anyway. Could also have been dropped completely, but probably not worth the additional effort.

**Comment by akva2** [comment]
did not notice. let's do it properly.

**Comment by akva2** [comment]
failure is due to known issue in opm-models. this does the job it's supposed to do so i'm merging as it is approved.

**Pull request merged**
