### PR TITLE
Bugfix in indexIn{In,Out}side method for PolyhedralGrid when used with corner point grids.

### PR DESCRIPTION
**Pull request by dr-robertk**
This PR fixes a problem with PolyhedralGrid when used with real corner point grids like Norne.

### CODE REVIEW

**Comment by dr-robertk** [comment]
jenkins build this please

**Comment by dr-robertk** [comment]
@atgeirr: It's ok to merge from my side.

**Comment by atgeirr** [comment]
> It's ok to merge from my side.

I don't have the time to look at it, but since it does not affect the CpGrid class I'm inclined to merge it anyway (tests are green). I'd like to do a compile test though, and that failed (in debug):

```
In file included from /Users/atgeirr/opm-build-debug/opm-grid/tests/grid_test.cc:8:
In file included from /Users/atgeirr/opm-build-debug/opm-grid/dune/grid/polyhedralgrid.hh:1:
/Users/atgeirr/opm-build-debug/opm-grid/dune/grid/polyhedralgrid/grid.hh:950:39: error: cannot refer to
      class template 'EntitySeed' without a template argument list
      assert( i>= 0 && i<subEntities( EntitySeed( seed.index() ) ) );
                                      ^
/Users/atgeirr/dune/dune-grid/dune/grid/common/grid.hh:358:54: note: template is declared here
  template<class GridImp, class EntitySeedImp> class EntitySeed;
                                                     ^
1 error generated.
```

**Comment by dr-robertk** [comment]
jenkins build this please

**Comment by dr-robertk** [comment]
I fixed the compile error.

**Comment by atgeirr** [comment]
> I fixed the compile error.

I can confirm that. Intend to merge this when Travis is green. Any particular reason to also invoke Jenkins?

**Comment by atgeirr** [comment]
It seems Jenkins finished first for this. I'll bite and merge this.

**Pull request merged**
