### PR TITLE
fix build without MPI

### PR DESCRIPTION
**Pull request by akva2**

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this serial please

**Comment by blattms** [comment]
Can you tell me what the error message was? I thought that I tested this in a serial build.

**Comment by akva2** [comment]
https://ci.opm-project.org/job/opm-grid/25/

**Comment by blattms** [comment]
Indeed. I somehow tested with `cmake -DBUILD_TESTING=OFF`, which does nit make much sense.

**Comment by blattms** [comment]
thanks for catching this.

**Comment by akva2** [comment]
folded into #405

**Pull request closed without merging**
