### PR TITLE
Change C arrays into std::vectors in test_graphofgrid

### PR DESCRIPTION
**Pull request by michal-toth**

### CODE REVIEW

**Comment by michal-toth** [comment]
jenkins build this please

**Comment by bska** [comment]
> Thanks for the quick fix! Merging.

Just out of curiosity: Did you verify that this fixes the CLang build?

**Comment by atgeirr** [comment]
> Just out of curiosity: Did you verify that this fixes the CLang build?

Yes, no warning anymore. However, there is another, unrelated in the same file:
```
/Users/atgeirr/opm/src/opm-grid/tests/test_graphofgrid.cpp:154:25: warning: adding 'value_type' (aka 'int') to a string does not append to the string [-Wstring-plus-int]
  153 |     std::string message("Expecting an error message from getGraphOfGridEdgeList, the vertex "
      |                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  154 |                         + gIDs[16] + std::string(" has a wrong number of edges."));
      |                         ^~~~~~~~~~
```
Can you fix this as well @michal-toth ?

**Comment by michal-toth** [comment]
Fix is on its way.

**Pull request merged**
