### PR TITLE
Hold global grid only on process (2nd try)

### PR DESCRIPTION
**Pull request by blattms**
This is my second try of #389. This time I did test with parallel Norne. This PR also includes @akva2's #403 to make it compile without MPI.

The fix is in commit 690e08c. The communication interfaces where not consistent if the cells had vertices besides their corners. Small bug with huge impact.

I would still like to run a test with another model, but I need to adjust it a bit since the parser is more strict
about whitespace now.

### CODE REVIEW

**Comment by blattms** [comment]
jenkins build this please

**Comment by akva2** [comment]
tested at my end:
norne on 4 procs is fine, norne on 8 procs is fine, norne on 32 procs is fine.

model2 starts fine on 16 procs, not finished. i don't really have an "expectation" to go after here but it's a fairly good sign that it has gotten quite far i'd say.

**Comment by blattms** [comment]
Yep, same here. seems to work as expected. since you are testing model2 I will skip that at my end.

**Comment by akva2** [comment]
i'm seeing some stalls on model 2, somewhat sensitive to the number of processes in use. i just got hold of this model and lack experience, but it seems suspicious, for instance 3 of 4 cores are pegged and one is hardly active. i think you have to investigate it. happens at report step 17 using the relaxed tolerances stuff.

**Comment by blattms** [comment]
Did you try with master, too?

**Comment by akva2** [comment]
working on it.

**Comment by blattms** [comment]
Definitely seeing a deadlock when running with 8 procs (which was not there in the last release). Will need to investigate what this is to and when it actually appeared.

**Comment by blattms** [comment]
With an updated master things are even worse. I am getting excessive time step chopping now. Might bedue to some other recent PRs (Solvers break down. Warnings about not finding bubble point pressures...)

I guess we might have a problem (not even/only contained in this PR).

**Comment by GitPaean** [comment]
> With an updated master things are even worse. 

By `updated` if you mean updated just now, then the https://github.com/OPM/opm-simulators/pull/1965# might be related, which was merged today and big.  It is a pure guess without any testing yet.  

> I am getting excessive time step chopping now. Might bedue to some other recent PRs (Solvers break down. Warnings about not finding bubble point pressures...)

Which case are you talking about here? Parallel or serial running?

**Comment by blattms** [comment]
Yep, same deadlock with current master.

@GitPaean I am talking about parallel model 2 and yes the PR you mentioned might very well be the cause for the chopping. It changes well code. Does it introduce group controls?

**Comment by GitPaean** [comment]
> Does it introduce group controls?

There was some group control before the PR, and the PR uses some different implementation. But I do not think model 2 has group control.

**Comment by akva2** [comment]
```
Thread 1 "flow" hit Catchpoint 1 (exception thrown), 0x00007ffff53f4ced in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
(gdb) where
#0  0x00007ffff53f4ced in __cxa_throw ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x0000555556f451b7 in Opm::WellsManager::createWellsFromSpecs<Dune::cpgrid::Cell2FacesContainer, Opm::UgGridHelpers::CpGridCentroidIterator<&(Dune::CpGrid::faceCentroid(int) const)>, Opm::GridPropertyAccess::Compressed<Opm::GridPropertyAccess::ArrayPolicy::ExtractFromDeck<double>, Opm::GridPropertyAccess::Tag::NTG> > (this=0x555564699350, wells=std::vector of length 13, capacity 16 = {...}, 
    timeStep=17, cart_dims=0x555559523108, dimensions=3, 
    well_names=std::vector of length 0, capacity 13, 
    well_data=std::vector of length 0, capacity 13, 
    well_names_to_index=std::map with 0 elements, phaseUsage=..., 
    cartesian_to_compressed=std::map with 18239 elements = {...}, 
    wells_on_proc=std::vector of length 13, capacity 13 = {...}, 
    ignored_wells=std::unordered_set with 20 elements = {...})
    at /home/akva/kode/opm/opm-simulators/opm/core/wells/WellsManager_impl.hpp:163
#2  0x0000555556efc6a5 in Opm::WellsManager::init<Dune::cpgrid::Cell2FacesContainer, Opm::UgGridHelpers::CpGridCentroidIterator<&(Dune::CpGrid::faceCentroid(int) const)> > (this=0x555564699350, eclipseState=..., schedule=..., 
    summaryState=..., timeStep=17, number_of_cells=18239, 
    global_cell=0x55556460de00, cart_dims=0x555559523108, dimensions=3, 
    cell_to_faces=..., begin_face_centroids=..., 
    deactivated_wells=std::unordered_set with 20 elements = {...})
---Type <return> to continue, or q <return> to quit---
    at /home/akva/kode/opm/opm-simulators/opm/core/wells/WellsManager_impl.hpp:362
#3  0x0000555556ec7b1a in Opm::WellsManager::WellsManager<Dune::cpgrid::Cell2FacesContainer, Opm::UgGridHelpers::CpGridCentroidIterator<&(Dune::CpGrid::faceCentroid(int) const)> > (this=0x555564699350, eclipseState=..., schedule=..., 
    summaryState=..., timeStep=17, number_of_cells=18239, 
    global_cell=0x55556460de00, cart_dims=0x555559523108, dimensions=3, 
    cell_to_faces=..., begin_face_centroids=..., is_parallel_run=true, 
    deactivated_wells=std::unordered_set with 20 elements = {...})
    at /home/akva/kode/opm/opm-simulators/opm/core/wells/WellsManager_impl.hpp:282
#4  0x0000555556e9126a in Opm::BlackoilWellModel<Opm::Properties::TTag::EclFlowProblem>::beginReportStep (this=0x5555595fdc00, timeStepIdx=17)
    at /home/akva/kode/opm/opm-simulators/opm/simulators/wells/BlackoilWellModel_impl.hpp:215
#5  0x0000555556f0b06a in Opm::BlackoilWellModel<Opm::Properties::TTag::EclFlowProblem>::beginEpisode (this=0x5555595fdc00)
    at /home/akva/kode/opm/opm-simulators/opm/simulators/wells/BlackoilWellModel.hpp:155
#6  0x0000555556ecb282 in Opm::EclProblem<Opm::Properties::TTag::EclFlowProblem>::beginEpisode (this=0x5555595fd5a0)
    at /home/akva/kode/opm/opm-simulators/ebos/eclproblem.hh:850
#7  0x0000555556e91d49 in Opm::BlackoilModelEbos<Opm::Properties::TTag::EclFlowP---Type <return> to continue, or q <return> to quit---
roblem>::beginReportStep (this=0x5555594e0760)
    at /home/akva/kode/opm/opm-simulators/opm/simulators/flow/BlackoilModelEbos.hpp:908
#8  0x0000555556e7aa30 in Opm::SimulatorFullyImplicitBlackoilEbos<Opm::Properties::TTag::EclFlowProblem>::run (this=0x5555595eae80, timer=...)
    at /home/akva/kode/opm/opm-simulators/opm/simulators/flow/SimulatorFullyImplicitBlackoilEbos.hpp:209
#9  0x0000555556e643ff in Opm::FlowMainEbos<Opm::Properties::TTag::EclFlowProblem>::runSimulator (this=0x7fffffffb040, output_cout=false)
    at /home/akva/kode/opm/opm-simulators/opm/simulators/flow/FlowMainEbos.hpp:468
#10 0x0000555556e56c6d in Opm::FlowMainEbos<Opm::Properties::TTag::EclFlowProblem>::execute (this=0x7fffffffb040, argc=2, argv=0x7fffffffdb38, 
    output_cout=false, output_to_files=true)
    at /home/akva/kode/opm/opm-simulators/opm/simulators/flow/FlowMainEbos.hpp:242
#11 0x0000555556df7683 in Opm::flowEbosBlackoilMain (argc=2, 
    argv=0x7fffffffdb38, outputCout=false, outputFiles=true)
    at /home/akva/kode/opm/opm-simulators/flow/flow_ebos_blackoil.cpp:63
#12 0x0000555556cd427c in main (argc=2, argv=0x7fffffffdb38)
    at /home/akva/kode/opm/opm-simulators/flow/flow.cpp:438
```

**Comment by akva2** [comment]
this is indeed within a completion loop,
```c++
                    if (cgit == cartesian_to_compressed.end()) {
                        const std::string msg = ("Cell with i,j,k indices " + std::to_string(i) + " " + std::to_string(j)
                                    + " " + std::to_string(k)  +  " not found in grid (well = " +  well.name() + ").");
                        OPM_THROW(std::runtime_error, msg);
                    }
```

**Comment by blattms** [comment]
I guess this is where it deadlocks for model2? That should definitely not happen. But why is the problem in master, too then? OPM/opm-simulators#2033 should not touch the code affecting this.

**Comment by akva2** [comment]
yes it's the deadlock. it's definitely not related to this PR. i have not found the time to go back to trace the regression, it's a bit involved with the back-and-forth across repos. hoped you'd have some idea, basically, we are referring a node that is not in our local to global map.

**Comment by akva2** [comment]
some more info.

using nightly builds, the last working version is 2019-07-21. it is then broken, not able to launch the case in 2019-07-28 until througout august. next working build i have is 2019-09-01, where the convergence problems for bubble point pressure etc appears.

**Comment by blattms** [comment]
Currently I am searching two regressions:

- timestepping breakdown in a parallel run. First occurence between Jul 15 and Aug 15 (at that time it was worse than ever >1000 steps in a report step).
- Deadlock

the first kind of prevents me from the second in a not so slow manner.

**Comment by blattms** [comment]
Maybe @joakim-hove can help:

Could be that the state of the EclipseState was changed in the past? In eclcpgridvanguard.hh We do:
```
//distribute the grid and switch to the distributed view.
{
       const auto wells = this->schedule().getWells2atEnd();
        defunctWellNames_ = std::get<1>(grid_->loadBalance(edgeWeightsMethod, &wells, faceTrans.data()));
}
```
And the assumption is that `wells` contains all wells with all connections that might be open at some
time during the simulation. One possible explanation of the deadlock that either a well is missing or
a connection is.

**Comment by blattms** [comment]
Time stepping issue was produced be me in the middle of August. Fix is in #406

**Comment by blattms** [comment]
Bisecting reveals that the deadlock appeared via OPM/opm-simulators#2033 (shame on me).

**Comment by blattms** [comment]
Superseded by the rebased version #418

**Pull request closed without merging**
