### PR TITLE
[feature][PolyhedralGrid] Allow to use coordinate type other than double.

### PR DESCRIPTION
**Pull request by dr-robertk**
This PR adds a template parameter to PolyhedralGrid allowing to set the coordinate type. The default is as before double.

### CODE REVIEW

**Comment by andlaus** [comment]
That's a good feature to have IMO. One question, though: what does this change? I suppose that the `UnstructuredGrid` structure stays as it is because of its C-nature?

**Comment by atgeirr** [comment]
jenkins build this with downstreams please

**Comment by dr-robertk** [comment]
Yes, UnstructuredGrid stays the same for now, but at least the upper layer  has the correct structure.

**Comment by atgeirr** [comment]
Thanks, merging!

**Pull request merged**
