### PR TITLE
Drop boost::iterator_range usage

### PR DESCRIPTION
**Pull request by akva2**
Motivation is to avoid parsing boost headers in downstream code.

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this please

**Comment by atgeirr** [comment]
A few comments:
 - Did you found the iterator_range classes somewhere? They have rather old copyright dates!
 - Why do we need the iterator_range_pod class? Should not pointer work nicely enough with the other ones?
 - I think the data members should be private, not public.

**Comment by blattms** [comment]
Missing companion PR in opm-upscaling

**Comment by akva2** [comment]
jenkins build this opm-upscaling=342 please

**Review by blattms — APPROVED** [review]
Looks good and is appreciated. Feel free to merge once jenkins is green

**Pull request merged**
