### PR TITLE
Prepare for use of clang-format

### PR DESCRIPTION
**Pull request by atgeirr**
With this, @joakim-hove, @bska and @atgeirr suggest that we start using clang-format to do automatic formatting, to reduce drudgery and nitpicking in our daily work and PR reviews.

This PR is intended to prepare for wide use of clang-format in all of OPM. We start with this module since the daily changes are limited.

Things to discuss:
 - Do we want to use a formatting tool like clang-format at all?
 - How to perform an initial re-formatting sweep of the module (esp. open PRs and similar problems).
 - Content of the style file, i.e. what formatting do we use.
 - How should we implement this in our daily workflows.
 - Do we enforce this, if so: how? Ideas include a reformatting git commit hook, a git commit hook that does not reformat but can deny unformatted code, jenkins support, other things.
 - Tool/editor support. We want to have all developers on board, and therefore to have a document describing how to obtain, use and integrate clang-format.

### CODE REVIEW

**Comment by atgeirr** [comment]
I have now drafted an initial version of the clang-format README, easiest to read in https://github.com/atgeirr/opm-grid/blob/prepare-clang-format/README-clang-format.md

There have been no comments so far on the proposed discussion items, so I'll start it myself, repeating the questions above:
 - *Do we want to use a formatting tool like clang-format at all?*
 -- Yes! It will help us avoid nitpicking and petty quarrels over code formatting, and therefore improve our developer lives!
 - How to perform an initial re-formatting sweep of the module (esp. open PRs and similar problems).
 -- Here in opm-grid I suggest we try to merge or close all open PRs first. For other modules, that will not work as there are too many in flight at any time, there I suggest we do it one directory at a time.
 - Content of the style file, i.e. what formatting do we use.
 -- The .clang-format file in this PR is my proposal. Please test it and see if it drives you nuts!
 - How should we implement this in our daily workflows.
 -- Initially I think we do this by applying to any new functions and files we write, and only occasionally apply it to whole existing files (after the initial reformatting).
 - Do we enforce this, if so: how? Ideas include a reformatting git commit hook, a git commit hook that does not reformat but can deny unformatted code, jenkins support, other things.
 -- I think: no. Too much can go wrong.
 - Tool/editor support. We want to have all developers on board, and therefore to have a document describing how to obtain, use and integrate clang-format.
 -- The README linked above aims to be such a document, but needs quality control and contributions from others (vim users, I'm looking at you).

**Comment by magnesj** [comment]
We have now applied clang-format to the whole application codebase in ResInsight. This is what we did:
1. Established a clang-format configuration in discussion with all developers
2. Applied clang-format on the whole codebase
3. Activated clang-format on save from our editors, in our case VS2017

See here for some notes
https://magnesj.github.io/resinsight-system-doc/system/clang-format-notes




So far we are really satisfied with

**Comment by atgeirr** [comment]
Thanks for your comment, I'll point to your page for Windows instructions!

**Comment by atgeirr** [comment]
Another point about re-formatting sweeps: a commit author such as "Autoformatter (clang-format)" should be used to easily distinguish from proper code changes.

I have now marked this no longer WIP, and intend to merge it tomorrow, unless discussions miraculously start now...

**Comment by blattms** [comment]
I am not experienced with clang-format, besides using it for a project where it was already used from the start. It seemed like it worked nicelym but sometimes it seemed to me as if the formatting it produced was slightly messed.

How sure are we that the results of applying clang-format match on all  the systems/versions that our quite diverse developer crowd uses? (I recall trying a proposed format file a while ago and it produced an error message.) I assume that @magnesj and colleagues might develop on the same system alltogether. If not, please comment.

As much as I like to be saved from nitpicks, I fear that the transition might cause a larger amount of merge conflicts due to whitespace changes. clang-format is usually applied on the whole file. At least in emacs the only sane/automatic way seems to be that you reformat during save. I know, that one can also do this on regions, but that is not possible automatically. Would I additionally get formatting instructions that emacs will be able to apply with its automatic indentation?

I assume that you intend to reformat all files (at least of a repository) at once. If there is on-going work of someone then how should he proceed? Is there a way besides rebasing onto the clang-format commit? That option will cause a lot of merge conflicts.

The proposed one-directory at a time might not work as this prevents automatic indentation.

IMHO there is no way around enforcing it. The question is how to enforce it? In dune we do fight trailing whitespace with a pre-commit hook that is installed when you run dunecontrol. That is not an option here.

**Comment by blattms** [comment]
BTW: Since I just saw that this is already merged (and I had a hook in emacs that searched for clang-format files in parent directories and use them during indentation): Please do not apply it here now since I am working on massive changes.

**Comment by atgeirr** [comment]
Thanks for your comments @blattms! I'll try to give my input on them (not in your order though):

> How sure are we that the results of applying clang-format match on all the systems/versions that our quite diverse developer crowd uses? (I recall trying a proposed format file a while ago and it produced an error message.) I assume that @magnesj and colleagues might develop on the same system alltogether. If not, please comment.

We cannot be sure of that. This is why I think we cannot enforce this strictly. So I disagree with this comment:

> IMHO there is no way around enforcing it.

... because we cannot avoid cases where due to differing versions we'll see oscillating formatting. (The only way around that is to do very little (as the dune eol whitespace thing) or require all developers to have a particular version. In addition requiring a formatting hook would be necessary.) Not enforcing this strictly would also avoid the situation you describe here:

> As much as I like to be saved from nitpicks, I fear that the transition might cause a larger amount of merge conflicts due to whitespace changes. clang-format is usually applied on the whole file.

You ask about integration:

> At least in emacs the only sane/automatic way seems to be that you reformat during save. I know, that one can also do this on regions, but that is not possible automatically. Would I additionally get formatting instructions that emacs will be able to apply with its automatic indentation?

Unfortunately I do not know. If anyone can contribute on this I would appreciate it.

> I assume that you intend to reformat all files (at least of a repository) at once. If there is on-going work of someone then how should he proceed? Is there a way besides rebasing onto the clang-format commit? That option will cause a lot of merge conflicts.

> BTW: Since I just saw that this is already merged (and I had a hook in emacs that searched for clang-format files in parent directories and use them during indentation): Please do not apply it here now since I am working on massive changes.

> The proposed one-directory at a time might not work as this prevents automatic indentation.

It will be very difficult to handle such a rebasing, which is why I proposed one directory at a time instead (avoiding any conflicts requiring a rebase). I do not understand your last comment, what does it have to do with automatic indentation? In any case, we'll not do anything drastic to opm-grid (or any other module) without consultation, we'll start somewhere else! Probably on the rewritten EclipseGrid class in opm-common (to get some concrete discussion).

**Comment by joakim-hove** [comment]
> At least in emacs the only sane/automatic way seems to be that you reformat during save. 

I have successfully bound the `reformat-region` function emacs to use `clang-format`; it is a bit in shambles right now, but it is my intention to post it here.

**Comment by joakim-hove** [comment]
> Please do not apply it here now since I am working on massive changes.

I guess one possibility was that when your ongoing work is complete and ready to be merged you amend with one extra reformatting commit. Then we have started.

**Comment by blattms** [comment]
> > At least in emacs the only sane/automatic way seems to be that you reformat during save. 
> 
> I have successfully bound the `reformat-region` function emacs to use `clang-format`; it is a bit in shambles right now, but it is my intention to post it here.
> 

Calling reformat-region is not automatic. I migth be an exception here, but
I am 100% sure that I will forget to make that call on the region I changed.

If emacs could determine the regions when I save only reformat them. That
would perfect. But that is way beyound my skillset to judge.

**Comment by joakim-hove** [comment]
> Calling reformat-region is not automatic.

No - that is true; I habitually type `M-=` as part of my ocd.

**Comment by blattms** [comment]
@atgeirr to clarify my concerns:

If we do not find either a way to enforce or to guide people how to automatically apply formatting, the following might happen:
1. Someone (probably me) forgets to trigger clang-format, commits commit a and pushes.
2. Developer A fixes this in a later commit as his editor does that automatically e.g. while saving. At the same time developer B works on a branch that includes commit a.
3. Conflicts -> rebase -> merge conflicts.

While there will be no more nitpicking by persons. the git workflow nitpicks in terms of merge conflicts.
Persons can be ignored, git not.

So to the very least we would need to decide to always clang-format-on-save if there is no other way to do this automatically with all editors.

**Comment by blattms** [comment]
BTW if we only clang-format in some directories, this complicates things and we might create a mess due to this added complexity.

**Comment by magnesj** [comment]
It can be useful to integrate clang-format on the build server. We haven't done it yet, but I think this can be useful as the workflows in OPM are much more diverse than we have in ResInsight (all developers use the same editor).

https://embeddedartistry.com/blog/2017/11/1/a-strategy-for-enforcing-formatting-with-your-build-server

**Comment by atgeirr** [comment]
> BTW if we only clang-format in some directories, this complicates things and we might create a mess due to this added complexity.

I did not mean that we should only do it in some directories, only that we could do the initial transformation one directory at a time. So if you work on foo/ we can reformat bar/, and when your work on foo/ is done we reformat that. The goal is to (quickly) get to the point where everything has been reformatted, but without requiring a period of "do not work on this module" that might be necessary otherwise.

**Comment by blattms** [comment]
Thanks for the link. That sound pretty nice and like a workable solution.
If I want a build that fails because of formatting to succeed, I download the
created patch, apply it, push, and retrigger the format step.

Thus we have enforcement and do not interfere with other established development
processes.

But I think the jenkins master @akva2 should comment here not me.

**Comment by akva2** [comment]
if you want clang-formatted diffs as part of the PR builds, I already have that prepared on another jenkins instance, though i would have to adjust it a little to get it working as we want it here (have to deal with the multiple repo things..). 

i do question if this is really wanted though, we will be completely at the mercy of clang format and its whims. in the other instance, we simply upload the diffs as artifacts, but do not alter build status.

**Comment by atgeirr** [comment]
> If we do not find either a way to enforce or to guide people how to automatically apply formatting, the following might happen:
> 
> 1. Someone (probably me) forgets to trigger clang-format, commits commit a and pushes.
> 2. Developer A fixes this in a later commit as his editor does that automatically e.g. while saving. At the same time developer B works on a branch that includes commit a.
> 3. Conflicts -> rebase -> merge conflicts.
> 
> While there will be no more nitpicking by persons. the git workflow nitpicks in terms of merge conflicts.
> Persons can be ignored, git not.

I agree, this can happen. What about the following rules:
 - Major reformatting happens in separate commits, using a designated author (as I proposed above).
 - Minor reformatting in a file you are working on for a feature is ok to include in that feature's commits, but is discouraged.
 - Reformatting in a file you are working on for a feature is fine to include in its PR, reformatting in other files must go in a separate PR.

I think that if we find a way to automatically enforce format-on-save for everyone, then your scenario does not happen, but I do not know if we can find such a way. If we do find it, then the problems of different versions etc. can lead to conflicts in any case, this is why I am not in favour of strict and automatic enforcement.

**Comment by atgeirr** [comment]
> if you want clang-formatted diffs as part of the PR builds, I already have that prepared on another jenkins instance, though i would have to adjust it a little to get it working as we want it here (have to deal with the multiple repo things..).
> 
> i do question if this is really wanted though, we will be completely at the mercy of clang format and its whims. in the other instance, we simply upload the diffs as artifacts, but do not alter build status.

What does this imply? That any commit will pass through a formatting filter before merging, adding extra commits to the PRs automatically?

**Comment by akva2** [comment]
nothing is automated. it just generates diff files and uploads those as artifacts of the build.

**Comment by atgeirr** [comment]
> nothing is automated. it just generates diff files and uploads those as artifacts of the build.

I see. Then I agree this seems like a workable middle ground.

**Comment by magnesj** [comment]
I vote for creation of diff files. If a clang-format change is detected, do not break the build. This can be enforced at a later stage if we see that clang-format diffs are rare.

**Comment by blattms** [comment]
Just asking myself whether we want to exclude certain files from formatting.
There have been and will be occasions where we copy upstream DUNE files to get
proposed bugfixes for older DUNE versions, too. It might be a bad idea to
change their indentation as this complicated keeping track of upstream changes.

**Pull request merged**
