### PR TITLE
fixed: include required headers where needed

### PR DESCRIPTION
**Pull request by akva2**
Due to changes upstream.

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this please

**Review by blattms — COMMENTED** [review]
I am a it surprised. Shouldn't all additional includes be guarded by `#if HAVE_ECL_INPUT`, or is there no difference?

**Comment by akva2** [comment]
uhm, tbh i am not sure. i assumed existing tests not having the guards was excluded on the build system level, but i did not confirm. in any case it is no worse with pr than it was before.

**Comment by blattms** [comment]
Me neither. Merging.

**Pull request merged**
