### PR TITLE
Remove parse

### PR DESCRIPTION
**Pull request by joakim-hove**
We currently have three logical grids:

1. The input grid `EclipseGrid` created by parsing the input.
2. The simulation grid, either `Dune::CpGrid` or `Opm::UnstructuredGrid`.
3. The output grid - written to disk as an EGRID file.

In particular the output grid is just a actnum adjusted version of the the input grid; this PR is a small step towards support of writing an EGRID representatio of the actual simulation grid.

1. The `Parser::parseFile( )` calls are removed from the `CpGrid` implementation; parsing input should be invoked in the application layer - not the library.
2. Removed the `Deck` based `CpGrid::processEclipseFormat()` overload - the `CpGrid::processEclipseFormat()` method should take an `EclipseGrid` instance.

Downstream: https://github.com/OPM/opm-upscaling/pull/188

### CODE REVIEW

**Comment by joakim-hove** [comment]
Ping?

**Comment by dr-robertk** [comment]
Great. I will have a look during this week.

**Comment by bska** [comment]
Since you're already in the area, I would **really** like to see `CpGrid::processEclipseFormat()` accept a `const EclipseGrid&` rather than a `EclipseGridConstPtr` parameter.

**Comment by joakim-hove** [comment]
> Since you're already in the area, I would really like to see CpGrid::processEclipseFormat() accept a const EclipseGrid& rather than a EclipseGridConstPtr parameter.

Yes I agree - however the large `std::shared_ptr<T>` diet as ongoing process; would like address this as part of that general change; but rest assured - it is underway.

**Comment by atgeirr** [comment]
Have not looked at this in detail yet, but I imagine there would be downstream changes to opm-upscaling from this (perhaps even quite few of them), have you looked into that?

**Comment by joakim-hove** [comment]
>but I imagine there would be downstream changes to opm-upscaling from this (perhaps even quite few of them), have you looked into that?

No - that was why I wanted downstream jenkins support. Can @atgeirr please post this comment:

```txt
jenkins build this with downstreams please
```

**Comment by atgeirr** [comment]
jenkins build this with downstreams please

**Comment by joakim-hove** [comment]
@akva2: Has the downstream build been invoked correctly? And is something happening?

**Comment by akva2** [comment]
it's easier to go to opm-project.org than to nag me. you are merging tons of pr's, there's a queue.

**Comment by joakim-hove** [comment]
> it's easier to go to ci.opm-project.org than to nag me.

OK sorry - will do.

**Comment by akva2** [comment]
heh, it's not a problem for me but if i weren't around you'd be sitting there waiting for my comment AND for the build to start ;)

**Comment by akva2** [comment]
there you go. maybe it should attach the executed tests even if another downstream failed to build. didn't consider those things in much detail..

**Comment by joakim-hove** [comment]
@abir type this comment please:

```txt
jenkins build this with downstreams opm-upscaling=188 please
```

**Comment by akva2** [comment]
jenkins build this with downstreams opm-upscaling=188 please

**Comment by akva2** [comment]
oh and for the future, it's not abir on github it's alfbr. some random guy is scratching his head right now ;)

**Comment by joakim-hove** [comment]
jenkins build this with downstreams opm-upscaling=188 please

**Comment by joakim-hove** [comment]
@alfbr  type this comment please:

```
jenkins build this with downstreams opm-upscaling=188 please
```

**Comment by alfbr** [comment]
jenkins build this with downstreams opm-upscaling=188 please

**Comment by joakim-hove** [comment]
The Jenkins downstream builder does not seem to fire; but it *works on my machine*&trade;. Unless someone objects I intend to merge this and the downstream:  OPM/opm-upscaling#188 later today.

**Pull request merged**
