### PR TITLE
Revert "Correctly support item 3 of PINCH (MAX_EMPTY_GAP)."

### PR DESCRIPTION
**Pull request by GitPaean**
Reverts OPM/opm-grid#658

### CODE REVIEW

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
I am okay with a fix from the current master branch or merging this PR before fixing the actual problem. But I think the jenkins test should be recovered as soon as possible.

**Comment by atgeirr** [comment]
@blattms Do you understand what went wrong, and can you fix this quickly? If it can be done within an hour or so we should avoid the revert, otherwise we should revert and redo the PR (with the as of now unknown fix).

**Comment by blattms** [comment]
When was that VAPPARS test added?

No I have no idea what happens here and why. I would need to take a look in the debugger and that takes time. I will try to take a look now.
Feel free to revert, but then I expect a timely review for the next PR. Lately, they have been hanging for quite some while....

**Comment by bska** [comment]
> but then I expect a timely review for the next PR. Lately, they have been hanging for quite some while....

Pot meet kettle...

**Comment by blattms** [comment]
Yeah, maybe it would be good idea to just ask for reviews on PRs. (At least that is what I often check if I am time pressed). That would make it easier to find the raisins between messages about e.g. branches just being force-pushed because of rebasing or impatient people announcing "I will self-merge tonight".

**Pull request merged**
