### PR TITLE
added: run distribution_test in parallel as well

### PR DESCRIPTION
**Pull request by akva2**
I would guess a serial execution of this test does not really test all parts of the code?

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this please

**Comment by blattms** [comment]
Just a question. A parallel test is always run in parallel with a fixed certain
number of processes?

**Comment by akva2** [comment]
yes, if we just run it normally that fixed number is 1, i now added a fixed number of 4. i can change to anything you'd like of course.

**Comment by akva2** [comment]
grml, stupid cmake version differences.

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
okay, now it passed. @blattms merge if you think this has additional value, i did not really look into what the test actually does.

**Comment by blattms** [comment]
Thanks. This certainly has value.

Is there a maximum runtime for parallel tests? Just in case we produce a deadlock...

**Comment by akva2** [comment]
ctest has a default of 1500s, but there's nothing apart from that.

**Pull request merged**
