### PR TITLE
Move files from opm/core/... and dune/grid/... to opm/grid/...

### PR DESCRIPTION
**Pull request by atgeirr**
As discussed in #306.

The only additional change is that I have renamed grid.h -> UnstructuredGrid.h (finally...)

Those who build code (that is not in OPM repositories) using these grids must change their include paths from dune/grid/CpGrid.hpp to opm/grid/CpGrid.hpp (for example). @dr-robertk, @berndflemisch  I imagine that could apply to you.

There are followup PRs in ewoms, opm-simulators and opm-upscaling.

### CODE REVIEW

**Comment by atgeirr** [comment]
jenkins build this ewoms=286 opm-upscaling=249 opm-simulators=1401 please

**Comment by atgeirr** [comment]
jenkins build this ewoms=286 opm-upscaling=249 opm-simulators=1401 please

**Comment by atgeirr** [comment]
jenkins build this ewoms=286 opm-upscaling=249 opm-simulators=1401 please

**Comment by atgeirr** [comment]
All green, but I'll not merge this on a weekend until people have had an opportunity to check the PR. I don't intend to keep it open for a long time though, the discussion was already open in #306.

**Comment by atgeirr** [comment]
jenkins build this ewoms=286 opm-upscaling=249 opm-simulators=1401 please

**Comment by akva2** [comment]
jenkins build this ewoms=286 opm-upscaling=249 opm-simulators=1401 opm-output=252 please

**Pull request merged**
