### PR TITLE
fixed: remove const qualifiers on value return types

### PR DESCRIPTION
**Pull request by akva2**
these are bad for RVO

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
RVO is maybe a bit imprecise. The standard rvo  is okay but const disables move semantics so further ellisions is not possible.

**Comment by bska** [comment]
>> May I ask why this influences RVO?
>
> The standard rvo is okay but const disables move semantics so further ellisions is not possible.

Correct, it's not so much RVO directly as it is move semantics and pr-values (or x-values).  If a function returns a `const T` with `T` being an object type, e.g. a built-in type like `double` or a user-defined class type like `std::array<>`, then the return value is not an x-value and the r-value category-based operators/constructors don't activate.

**Comment by bska** [comment]
> Are you guys sure we are moving here? Seems like for all these functions the return objects are created (without name) in the return statement. Isn't this exactly where unnamed RVO should kick in?

It's not RVO.  Code like
```C++
class X { /* ... */ };
const X f();
X g();
// ...
const auto x = f();
const auto y = g();
```
works perfectly and will construct both `x` and `y` in place.  However
```C++
std::vector<X> x;
// ...
x.push_back(f()); // (1)
x.push_back(g()); // (2)
```
will call `push_back(const X&)` for (1) and `push_back(X&&)` for (2).  That might matter.

**Comment by akva2** [comment]
closing as it will be handled elsewhere.

**Pull request closed without merging**
