### PR TITLE
adding ndims to omp shared to fix the compilation problem

### PR DESCRIPTION
**Pull request by GitPaean**
the compilation issue is descriped in OPM/opm-grid#438

this closes OPM/opm-grid#438

Thank @atgeirr for suggesting the fix.

### CODE REVIEW

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by atgeirr** [comment]
> yes this is the correct fix.

Any idea why it was not triggered before? Compiler error?!?

**Comment by akva2** [comment]
i can't really say why it was not triggered before as it has always been an error since default is set to none. i guess bugs in gcc version related to optimization?

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by atgeirr** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
Looks like we ran into different openmp support from different versions of compilers now. 

```
/var/lib/jenkins/workspace/opm-grid-PR-builder/opm/grid/cpgpreprocess/geometry.c: In function 'compute_face_geometry_3d':
/var/lib/jenkins/workspace/opm-grid-PR-builder/opm/grid/cpgpreprocess/geometry.c:60:11: error: 'ndims' is predetermined 'shared' for 'shared'
     shared(fnormals,fcentroids,fareas  \
           ^
/var/lib/jenkins/workspace/opm-grid-PR-builder/opm/grid/cpgpreprocess/geometry.c: In function 'compute_cell_geometry_3d':
/var/lib/jenkins/workspace/opm-grid-PR-builder/opm/grid/cpgpreprocess/geometry.c:240:10: error: 'ndims' is predetermined 'shared' for 'shared'
    shared(coords,nodepos,facenodes,neighbors,twothirds,  \
          ^
CMakeFiles/opmgrid.dir/build.make:542: recipe for target 'CMakeFiles/opmgrid.dir/opm/grid/cpgpreprocess/geometry.c.o' failed
make[2]: *** [CMakeFiles/opmgrid.dir/opm/grid/cpgpreprocess/geometry.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:1326: recipe for target 'CMakeFiles/opmgrid.dir/all' failed
```

**Comment by GitPaean** [comment]
Let us see anything is changed after the jenkins upgrade.

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
i added you to white list now (i also triggered so for next time..)

**Comment by GitPaean** [comment]
Thanks @akva2

**Comment by GitPaean** [comment]
Some information is telling since ndims is const, it should not be added to the `shared`.  I am no expert in this.

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
It looks like the version of compiler on Jenkins still does not like this change.  I will close it now.  I will add a note to the issue #438

**Comment by GitPaean** [comment]
I am reopening it now for more discussion.  It looks like the failure #438 is caused by using GCC 9.0+ (not totally sure which version changes the behavior), while the change in this PR will cause problem for GCC older than GCC9

**Comment by GitPaean** [comment]
This compatibility can also be a problem for clang80/90.

**Comment by GitPaean** [comment]
@akva2 , I added some macro to check the version of GCC.  It looks like the compatibility problem will appear sooner or later with new compilers. both for GCC and Clang.

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
jenkins gave green. @akva2 , you can suggest what is the good way to go. 

We can also remove `default(none)`.

**Comment by akva2** [comment]
if removing default(none) would fix it, it's less intrusive for sure. if not, we can eat the ifdef though it is rather ugly (at least it's not our uglyness).

**Comment by GitPaean** [comment]
I removed `default(none)`.  Not sure whether it brings any impact in term of performance. 

I am no expert in this at all.

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by akva2** [comment]
there is no impact on performance, the default is shared. it just means you have to (well, should have to) be explicit about all variables in the scope.

**Pull request merged**
