### PR TITLE
fix build with dune 2.4 after PR #416

### PR DESCRIPTION
**Pull request by akva2**

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this dune2.4 please

**Comment by akva2** [comment]
@dr-robertk while this does the job, i'm afraid it's not a proper fix since the HAVE_DUNE_GRID_CHECK is also false on my system, and it compiles without them. please advice.

**Comment by dr-robertk** [comment]
@akva2: Thanks for looking into this. The HAVE_DUNE_GRID_CHECK is a good idea. I think you could just use #ifdef DUNE_GRID_TEST_GRIDCHECK_HH which is the header guard for this. It's also fine if this gridcheck is just disabled for dune2.4 because these newer features should only be used with a fairly new DUNE version.

**Comment by akva2** [comment]
okay, i made it dependent on dune >= 2.5 like the header include.

**Comment by akva2** [comment]
jenkins build this dune2.4 please

**Comment by dr-robertk** [comment]
@akva2: Thanks for fixing this. Just merge it please when the tests go through.

**Pull request merged**
