### PR TITLE
[mpi] Never increment end iterator in gatherv.

### PR DESCRIPTION
**Pull request by blattms**
Even if some do not care (but should) as we never decrement, it is undefined behavior according to the STL. Hence let's do proper code.

Kudos to @bska for the hint. (Learning never stops.)

### CODE REVIEW

**Comment by blattms** [comment]
jenkins build this please

**Comment by blattms** [comment]
if-branch is indeed more readable. Will change.

**Comment by blattms** [comment]
jenkins build this please

**Review by bska — APPROVED** [review]
Thanks.  This looks good to me and the build check is green.  I'll merge into master.

**Pull request merged**
