### PR TITLE
Save/export information about Numerical Aquifer cells in CpGrid.

### PR DESCRIPTION
**Pull request by blattms**
This is done as a sorted range of active indices of aquifer cells. The information is communicated during loadbalance.

For parallel testing we use a data file from opm-tests.

Is there a way to deactivate the serial test? It is rather useless...

### CODE REVIEW

**Comment by ytelses** [comment]
Benchmark result overview: 




| Test    | Configuration                                     | Relative |
| ------- | ------------------------------------------------- | -------- |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 1        | 1.011    |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 8        | 1.008    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1        | 0.981    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8        | 0.995    |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 1 | 0.997    |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 8 | 0.99     |
* Speed-up = Total time master / Total time pull request. Above 1.0 is an improvement. *



View result details @ https://www.ytelses.com/opm/?page=result&id=1394

**Comment by blattms** [comment]
@akva2 That suggestion sounded very easy, but I seem to missing all necessary skills. How do I get the to run in parallel?
Using
```
  opm_add_test(cpgrid_aquifer_test
    SOURCES tests/cpgrid/cpgrid_aquifer_test.cpp
    DEPENDS opmgrid
    PROCESSORS 4
    CONDITION MPI_FOUND AND Boost_UNIT_TEST_FRAMEWORK_FOUND
    DRIVER_ARGS -np 4
    TEST_ARGS -- ${OPM_TESTS_ROOT}/aquifer-num/3D_2AQU_NUM.DATA
    LIBRARIES opmgrid ${Boost_UNIT_TEST_FRAMEWORK_LIBRARY})
``
Adding "DRIVER mpirun" at least uses mpirun but passes the binary with the '-e' option which mpirun does not support.
Is there an existing driver script for this?

**Comment by akva2** [comment]
there is a driver but not in omp-grid. see https://github.com/OPM/opm-simulators/blob/master/CMakeLists.txt#L286 and https://github.com/OPM/opm-simulators/blob/master/tests/run-parallel-unitTest.sh

**Comment by blattms** [comment]
Maybe we should move that to opm-common?

**Comment by akva2** [comment]
yes probably. simply has been no need yet. you'd have to do some extra dancing to pull that off though (to pass it through the installed build chain), so nobody would object if you simply copy-pasta for now and then we'll deal with it separately.

**Comment by blattms** [comment]
Well, then I can just use add_test directly instead. Seems less work.

**Comment by blattms** [comment]
Ok, I tried this but the result a47717f  seems worse than what was there before.

**Comment by totto82** [comment]
jenkins build this please

**Pull request merged**
