### PR TITLE
Remove unused file

### PR DESCRIPTION
**Pull request by joakim-hove**
Not used -

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by blattms** [comment]
> Not used -

Seems like the worst title ever. No matter how big the pressure is, we should always try use self-explanatory titles (ideally with some good description). Otherwise we make the lives of our colleagues that have to do some bisection to find bugs really miserable.

**Comment by blattms** [comment]
I do not seem to be awake, sorry. That was not the title. Together with it suffices. My apologies for barking.

**Pull request merged**
