### PR TITLE
[fix] Remove last_patch_cells

### PR DESCRIPTION
**Pull request by aritorto**
Unnecessary and wrong insert on the vector containing all the cell indices to be refined has been deleted.

### CODE REVIEW

**Comment by aritorto** [comment]
jenkins build this serial please

**Comment by akva2** [comment]
please consider if you really need serial in all your triggers, we are rather pressed on ci resources these days.

**Comment by aritorto** [comment]
Oh, I wasn't aware. I'll keep it mind next time. It's my default jenkins instruction. Which one would be more suitable?

**Review by blattms — APPROVED** [review]
Thanks a lot for finding and fixing this.

**Pull request merged**
