### PR TITLE
Implement GridHelper createACTNUM() based on manual overload

### PR DESCRIPTION
**Pull request by joakim-hove**
Hmm - struggled getting the template based solution in #428 to compile from opm-simulators.

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by blattms** [comment]
What was the struggle?

Using overloading is fine of course.

**Comment by joakim-hove** [comment]
> What was the struggle?

To be 100% honest - I don't really know - the number of moving parts is quite high on my machine; but the end result was at least that `flow` would not link. The simple overload based method works - and "works" is hard to beat when Christmas is approaching.

**Comment by blattms** [comment]
Here you are: :hammer: :nails:

**Pull request merged**
