### PR TITLE
passing correct cell_comm_ communicator

### PR DESCRIPTION
**Pull request by ElyesAhmed**
The CpGridData  was not taking the correct communicator

### CODE REVIEW

**Comment by atgeirr** [comment]
jenkins build this please

**Comment by blattms** [comment]
Good catch and probably hard to find.

I guess it is high time to add a correct test as outlined in [comment](https://github.com/OPM/opm-simulators/pull/3571#issuecomment-936268832) of OPM/opm-simulators#3571 here as in opm-simulators.

**Comment by blattms** [comment]
While at it, please also fix the constructors `CpGridData::CpGridData(CpGrid&)`and/or a `CpGridData::CpGridData(CpGridData&)`
accordingly. In the latter we also need to initialize `ccobj_` corrrectly (still taking MPI_COMM_WORLD).

**Comment by ElyesAhmed** [comment]
> Good catch and probably hard to find.
> 
> I guess it is high time to add a correct test as outlined in [comment](https://github.com/OPM/opm-simulators/pull/3571#issuecomment-936268832) of [OPM/opm-simulators#3571](https://github.com/OPM/opm-simulators/pull/3571) here as in opm-simulators.

Yes, and adding a test is more than urgent now!

**Comment by ElyesAhmed** [comment]
> While at it, please also fix the constructors `CpGridData::CpGridData(CpGrid&)`and/or a `CpGridData::CpGridData(CpGridData&)` accordingly. In the latter we also need to initialize `ccobj_` corrrectly (still taking MPI_COMM_WORLD).

fixed in both calls now!

**Comment by atgeirr** [comment]
Code changes look good, thanks @blattms for pointing out that the other constructors also needed care.

@ElyesAhmed please rebase so there is only a single commit here. PRs must not include merge commits, in particular.

**Comment by blattms** [comment]
jenkins build this please

**Comment by bska** [comment]
Hi @ElyesAhmed.  Thanks for the updates&mdash;I think the code here looks reasonable now.  Would you be able to "rebase" the PR on top of the current master sources?  Doing so will remove the merge commit and make the commit history "nicer" later on.

**Comment by ElyesAhmed** [comment]
> Hi @ElyesAhmed. Thanks for the updates—I think the code here looks reasonable now. Would you be able to "rebase" the PR on top of the current master sources? Doing so will remove the merge commit and make the commit history "nicer" later on.

I don't know how to rebase without a forced push!

**Comment by atgeirr** [comment]
jenkins build this please

**Comment by akva2** [comment]
there is no such thing as a rebase without force push so it is good that you do not know how to do it without.

**Comment by blattms** [comment]
I think he meant: Force pushing obn branches of PRs is ok as normally only
one person is working on it. Master and branches where people collaborate that is
a different story, of course.

**Comment by blattms** [comment]
@ElyesAhmed I am a bit confused. Seems like you removed how cell_comm_ is initialized in fbd4c73

**Comment by ElyesAhmed** [comment]
> @ElyesAhmed I am a bit confused. Seems like you removed how cell_comm_ is initialized in [fbd4c73](https://github.com/OPM/opm-grid/commit/fbd4c7312efbdebd6f6d0a5d6ffdae0e5aa9647c)

No, as this  OwnerOverlap communication  for cells cell_comm_ for  is only introduced If we have MPI. Otherwise the serial compilation cannot be done without this change!

**Comment by blattms** [comment]
Thanks, somehow missed that.

Will you do the requested clean & squashing? If that is troublesome for you, mabye @atgeirr or I should do that?

**Comment by ElyesAhmed** [comment]
> Thanks, somehow missed that.
> 
> Will you do the requested clean & squashing? If that is troublesome for you, mabye @atgeirr or I should do that?

 ok

**Comment by atgeirr** [comment]
jenkins build this serial please

**Pull request merged**
