### PR TITLE
Fixes fallout from PR #477.

### PR DESCRIPTION
**Pull request by blattms**
Some people even manage to mess up when trying to clarify logical
expressions in code. Thos need to updated in a cell loop, of course.
Otherwise information is wrong-

### CODE REVIEW

**Comment by blattms** [comment]
Still misses a test that would have failed before.

**Comment by blattms** [comment]
Maybe one of the existing tests is even false now? Let's check.

**Comment by blattms** [comment]
jenkins build this please

**Comment by alfbr** [comment]
Excellent, it works!

**Review by alfbr — APPROVED** [review]

**Review by bska — APPROVED** [review]
Very good.  I'll merge into master.

**Pull request merged**
