### PR TITLE
[cleanup] Removed workaround for DUNE <2.4 bug.

### PR DESCRIPTION
**Pull request by blattms**
We do not support it anymore.

### CODE REVIEW

**Comment by blattms** [comment]
jenkins build this please

**Comment by akva2** [comment]
uhm, we support 2.4 still unless i've failed to be notified. the comment indicates it's pre 2.4 ?

**Comment by blattms** [comment]
Indeed, it is <2.4 that this drops. Just double checked, Upstream fix is in commit [20309d46](https://gitlab.dune-project.org/core/dune-common/commit/20309d4698c1c2797433f811f52d17e8129634b9)
Will reword.

**Comment by blattms** [comment]
Done.

**Comment by blattms** [comment]
jenkins build this please

**Comment by blattms** [comment]
I guess this was already done via #418

**Pull request closed without merging**
