### PR TITLE
Complete refined geometry of a single cell.

### PR DESCRIPTION
**Pull request by aritorto**
Refined face geometries added. Refined corner numbering consistent with
cpgrid. Small corrections on corner indices and addition of face
indices in the construction of refined cells. Extended check for the eight
refined corners that coincide with the parent cell corners.

Next steps:
1. To include topology of the refined cell.
2. To refine a patch of cells.

### CODE REVIEW

**Comment by blattms** [comment]
jenkins build this please

**Comment by atgeirr** [comment]
Congrats on your first PR to opm-grid @aritorto!

Looked only briefly at it, and there are some really long functions here, but it all looks very well commented, which is good. @blattms what is the time schedule for reviewing this? If feasible I would like to keep myself updated on this part of the code.

**Comment by blattms** [comment]
> @blattms what is the time schedule for reviewing this? If feasible I would like to keep myself updated on this part of the code.

Not sure what you mean. Do you want to review this and are asking me how much time you have? Or are you asking me when I will find time to review?

**Comment by atgeirr** [comment]
> Not sure what you mean. Do you want to review this and are asking me how much time you have? Or are you asking me when I will find time to review?

Both... To be clear:
 - Will you review this?
 - If so, when will you review this?
 - Is there a schedule/time constraint for when it should be merged?

**Comment by blattms** [comment]
If nobody else has time I can review this, of course. Of course I have somewhat been involved in the making and might bnot be 100% objective. But if that is not  a problem, I am fine with reviewing. Would review it these days. 

We will build on this PR (there are even now quite some things missing). For that it does not have to b merged, but it would help to have no big breaking changes requested. It will be a rather iterative process and there will be quite a few PRs with changes.

I hear that you think that @aritorto should try to shorten it. Sounds like a good idea. We will discuss this then.

**Comment by aritorto** [comment]
We reduced the code for the construction of the refined faces (one loop instead of three), and removed non necessary containers.

**Comment by blattms** [comment]
jenkins build this please

**Comment by blattms** [comment]
We have gone through some internal reviews with this and at least shortened the code for the face computations. While this is still a first step (refine only one cell), it does already use the data structures of CpGridData to prepare for the real levels, fixes a few issues with the previous version, and adds the missing faces. There is also a pending PR (to be published today or tomorrow).

From my side this is approved (we might improve it further later) and I would like to merge this. I intend to do this tomorrow afternoon to give others time to comment.

**Comment by atgeirr** [comment]
> From my side this is approved (we might improve it further later) and I would like to merge this. I intend to do this tomorrow afternoon to give others time to comment.

Thanks for the heads-up, I will try to make time for a reading today, then.

**Comment by aritorto** [comment]
Closing this in favor of #594, where tests are included.

**Pull request closed without merging**
